document.writeln("<script language=\"javascript\" type=\"text/javascript\">");
document.writeln("function plancont()");
document.writeln("{");
document.writeln("$(\"#plandt\").css(\"display\",\"none\");	");
document.writeln("var htmlobj=$.ajax({url:\"/index.php/vod/opt/new\",async:false});");
document.writeln("if(htmlobj.responseText!=\"0\")");
document.writeln("{");
document.writeln("$(\"#plandt\").css(\"display\",\"\");");
document.writeln("$(\"#plandt\").html(htmlobj.responseText);");
document.writeln("}");
document.writeln("}");
document.writeln("setInterval(\"plancont()\",10000); ");
document.writeln("</script>");
document.writeln("<script language=\"javascript\" type=\"text/javascript\">");
document.writeln("function hdm1()");
document.writeln("{");
document.writeln("$(\"#hdm1\").css(\"display\",\"none\");	");
document.writeln("var htmlobj=$.ajax({url:\"/index.php/page/index/hdm1\",async:false});");
document.writeln("if(htmlobj.responseText!=\"0\")");
document.writeln("{");
document.writeln("$(\"#hdm1\").css(\"display\",\"\");");
document.writeln("$(\"#hdm1\").html(htmlobj.responseText);");
document.writeln("}");
document.writeln("}");
document.writeln("setInterval(\"hdm1()\",20000); ");
document.writeln("</script>");
document.writeln("<script language=\"javascript\" type=\"text/javascript\">");
document.writeln("function hdm2()");
document.writeln("{");
document.writeln("$(\"#hdm2\").css(\"display\",\"none\");	");
document.writeln("var htmlobj=$.ajax({url:\"/index.php/page/index/hdm2\",async:false});");
document.writeln("if(htmlobj.responseText!=\"0\")");
document.writeln("{");
document.writeln("$(\"#hdm2\").css(\"display\",\"\");");
document.writeln("$(\"#hdm2\").html(htmlobj.responseText);");
document.writeln("}");
document.writeln("}");
document.writeln("setInterval(\"hdm2()\",20000); ");
document.writeln("</script>");
document.writeln("<script language=\"javascript\" type=\"text/javascript\">");
document.writeln("function hdm3()");
document.writeln("{");
document.writeln("$(\"#hdm3\").css(\"display\",\"none\");	");
document.writeln("var htmlobj=$.ajax({url:\"/index.php/page/index/hdm3\",async:false});");
document.writeln("if(htmlobj.responseText!=\"0\")");
document.writeln("{");
document.writeln("$(\"#hdm3\").css(\"display\",\"\");");
document.writeln("$(\"#hdm3\").html(htmlobj.responseText);");
document.writeln("}");
document.writeln("}");
document.writeln("setInterval(\"hdm3()\",20000); ");
document.writeln("</script>");